QLVB-V1/QLVB2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from QLVB2_APP import views
from offenses import views 
# import QLVB2_APP , offenses

urlpatterns = [
    url('admin/', admin.site.urls),
    # url('^$',ql.views.index, name='index'),
    url('',include('QLVB2_APP.urls')),
    # url('',include('offenses.urls')),
]

QLVB-V1/QLVB2_APP/urls.py
from django.conf.urls import url
from django.urls import path
from QLVB2_APP import views
from .views import *
from offenses.views import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'QLVB2_APP'

urlpatterns = [
    url('register/', views.register, name='register'),
    url('login/', views.login, name='login'),
    url('logoutUser/', views.logoutUser, name='logout'),

    url(r'^$',views.index, name='index'),
    url(r'^congtacchuyenmon/$', views.congtacchuyenmon, name='congtacchuyenmon'),
    url(r'^tongsocongviec/$',views.tongsocongviec, name='tongsocongviec'),
    url(r'^hoanthanh/$', views.hoanthanh, name='hoanthanh'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^dangthuchien/$', views.dangthuchien, name='dangthuchien'),
    url(r'^chamtiendo/$', views.chamtiendo, name='chamtiendo'),
    url(r'^giahan/$', views.giahan, name='giahan'),
    url(r'^nhapdulieuchuyenmon/$', views.nhapdulieu_chuyenmon, name='nhapdulieu_chuyenmon'),
    url(r'^bangcap/$', views.bangcap, name='bangcap'),
    url(r'^taisan/$', views.taisan, name='taisan'),
    url(r'^dulieubaocaotuan/$', views.dulieubaocaotuan, name='dulieubaocaotuan'),


    path('edit_congviec/<str:pk>/', views.edit_congviec, name="edit_congviec"),
    path('delete_congviec/<str:pk>/', views.delete_congviec, name="delete_congviec"),

    path('edit_taisan/<str:pk>/', views.edit_taisan, name="edit_taisan"),
    path('delete_taisan/<str:pk>/', views.delete_taisan, name="delete_taisan"),

    path('edit_bangcap/<str:pk>/', views.edit_bangcap, name="edit_bangcap"),
    path('delete_bangcap/<str:pk>/', views.delete_bangcap, name="delete_bangcap"),

    path('edit_bctuan/<str:pk>/', views.edit_bctuan, name="edit_bctuan"),


    url(r'^csv/$', views.export_csv, name='export_csv'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

QLVB-V1/QLVB2_APP/models.py
from django.db import models
from datetime import datetime, date
# Create your models here.


class thuchien_m(models.Model):
    thuchien_name = models.CharField(max_length=264)

    def __str__(self):
        return self.thuchien_name

class tiendo(models.Model):
    tiendo_name = models.CharField(max_length=264)

    def __str__(self):
        return self.tiendo_name

# models congtacchuyenmon
class themmoi_m(models.Model):
    stt_name = models.AutoField(primary_key=True)
    doidung_name = models.CharField(max_length=1000)
    thuchien_name = models.ForeignKey(thuchien_m, on_delete=models.CASCADE)
    batdau_name = models.DateField(auto_now_add=True, blank=True)
    ketthuc_name = models.DateField()
    tiendo_name = models.ForeignKey(tiendo, on_delete=models.CASCADE)
    Ghichu_name = models.CharField(max_length=1000)

    def __str__(self):
        return self.doidung_name
class bangcap_m(models.Model):
    stt_bc = models.AutoField(primary_key=True)
    hovaten_bc = models.CharField(max_length=1000)
    bangcap_bc = models.CharField(max_length=1000)
    chungchi_bc = models.CharField(max_length=1000)
    Ghichu_bc = models.CharField(max_length=1000)

    def __str__(self):
        return self.hovaten_bc

class taisan_m(models.Model):
    stt_ts = models.AutoField(primary_key=True)
    tenloai_ts = models.CharField(max_length=1000)
    maso_ts = models.CharField(max_length=1000)
    namduavaosudung_ts = models.DateField()
    soluong_ts_ss = models.CharField(max_length=1000)
    nguyengia_ts_ss = models.CharField(max_length=1000)
    soluong_ts_kk = models.CharField(max_length=1000)
    nguyengia_ts_kk = models.CharField(max_length=1000)
    ghichu_ts = models.CharField(max_length=1000)

    def __str__(self):
        return self.tenloai_ts

class bctuan_m(models.Model):
    stt_bct = models.AutoField(primary_key=True)
    noidung_bct= models.CharField(max_length=10000)
    ghichu_bct = models.CharField(max_length=10000)

    def __str__(self):
        return self.noidung_bct

# models thong ke su co
class duongdan_m(models.Model):
    nguoiupload = models.CharField(max_length=10000, null=True)
    tenfile = models.CharField (max_length=10000, null=True)
    ngayup = models.DateField(auto_now_add=True, null=True)
    duongdan= models.FileField(upload_to='')

    def __str__(self):
        return self.tenfile

QLVB-V1/QLVB2_APP/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django .contrib.auth.models import User
from QLVB2_APP.models import  themmoi_m, tiendo, thuchien_m, bangcap_m, taisan_m, bctuan_m, duongdan_m
from QLVB2_APP import views
from datetime import datetime, date, timedelta
from django.utils.timezone import datetime

# ...................
class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email','password1', 'password2' ]



class themmoi_f(forms.ModelForm):
    doidung_name = forms.CharField(widget=forms.Textarea, required=True)
    thuchien_name = forms.ModelChoiceField(queryset=thuchien_m.objects.filter(),required=True)
    ketthuc_name = forms.DateTimeInput()
    tiendo_name = forms.ModelChoiceField(queryset=tiendo.objects.all(), required=True)
    Ghichu_name = forms.CharField(widget=forms.Textarea, required=True)

    class Meta():
        model = themmoi_m
        fields = ("__all__")


# bang bangcap
class bangcap_f(forms.ModelForm):
    hovaten_bc = forms.CharField(widget=forms.Textarea, required=True)
    bangcap_bc = forms.CharField(widget=forms.Textarea, required=True)
    chungchi_bc = forms.CharField(widget=forms.Textarea, required=True)
    Ghichu_bc = forms.CharField(widget=forms.Textarea, required=True)

    class Meta():
        model = bangcap_m
        fields = ("__all__")

class taisan_f(forms.ModelForm):
    tenloai_ts = forms.CharField(max_length=1000)
    maso_ts = forms.CharField(max_length=1000,required=False)
    namduavaosudung_ts = forms.DateField()
    soluong_ts_ss = forms.CharField(max_length=1000,required=False)
    nguyengia_ts_ss = forms.CharField(max_length=1000,required=False)
    soluong_ts_kk = forms.CharField(max_length=1000,required=False)
    nguyengia_ts_kk = forms.CharField(max_length=1000,required=False)
    ghichu_ts = forms.CharField(max_length=1000,required=False)

    class Meta():
        model = taisan_m
        fields = ("__all__")

class bctuan_f(forms.ModelForm):
    # stt_bct = forms.CharField(max_length=1000)
    noidung_bct = forms.CharField(widget=forms.Textarea, required=True)
    ghichu_bct = forms.CharField(widget=forms.Textarea, required=True)

    class Meta():
        model = bctuan_m
        fields = ("__all__")

class uploadform_f(forms.ModelForm):
    tenfile = forms.CharField (max_length=10000, required=False)
    nguoiupload = forms.CharField (max_length=10000, required=False)
    # nguoiupload =
    # ngayup = forms.DateField(null=True)
    # duongdan= forms.FileField()

    class Meta():
        model = duongdan_m
        fields = ("__all__")

QLVB-V1/QLVB2_APP/views.py
from django.shortcuts import render, redirect, get_object_or_404
from QLVB2_APP.models import themmoi_m, tiendo, thuchien_m, bangcap_m, taisan_m, bctuan_m, duongdan_m
from django.db.models import Count
from django.contrib.auth.forms import UserCreationForm
from . import forms
import datetime
from datetime import timedelta
from .filters import tongsofilter
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login as dj_login
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import csv
from django.http import HttpResponse

from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
# Create your views here.

def register(request):
    if request.user.is_authenticated:
        return redirect('QLVB2_APP:index')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form =CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Tài khoản được đăng ký thành công' + user)

                return redirect('QLVB2_APP:login')

        context = {'form':form}
        return render(request, 'QLVB2_APP/register.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('QLVB2_APP:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username =username, password = password)
            if user is not None:
                dj_login(request, user)
                return redirect ('QLVB2_APP:index')
            else:
                messages.info(request, 'Tài khoản hoặc mật khẩu không đúng')

        context={}
        return render(request, 'QLVB2_APP/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('QLVB2_APP:login')


# @login_required(login_url='QLVB2_APP:login')
def index(request):
    orderlist_=['tiendo_name', 'ketthuc_name']
    danhmuc_congtacchuyenmon = themmoi_m.objects.all().order_by(*orderlist_)
    tiendo_data = tiendo.objects.all()
    thuchien_data = thuchien_m.objects.all()
    bctuan_data = bctuan_m.objects.order_by('-stt_bct')[:1]
    Myfilter = tongsofilter(request.GET, queryset=danhmuc_congtacchuyenmon)
    danhmuc_congtacchuyenmon = Myfilter.qs
    soluong = danhmuc_congtacchuyenmon.count()
    cham = danhmuc_congtacchuyenmon.filter(tiendo_name='3').count()
    hoanthanh = danhmuc_congtacchuyenmon.filter(tiendo_name='2').count()
    dangthuchien = danhmuc_congtacchuyenmon.filter(tiendo_name='1').count()
    giahan = danhmuc_congtacchuyenmon.filter(tiendo_name='4').count()

    # view pages
    page = request.GET.get('page', 1)
    paginator = Paginator(danhmuc_congtacchuyenmon, 5)
    try:
        page_hienthi = paginator.page(page)
    except PageNotAnInteger:
        page_hienthi =  paginator.page(1)
    except EmptyPage:
        page_hienthi = paginator.page(paginator.num_pages)

    return render(request, 'QLVB2_APP/index.html',context={'congtacchuyenmon_record':danhmuc_congtacchuyenmon,
                                                            'soluong':soluong, 'cham':cham, 'hoanthanh':hoanthanh,
                                                            'dangthuchien':dangthuchien,'giahan':giahan,
                                                            'Myfilter':Myfilter, 'tiendo_data': tiendo_data,
                                                            'thuchien_data':thuchien_data, 'page_hienthi':page_hienthi,
                                                            'bctuan_data':bctuan_data})
# export csv
def export_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment;filename="solieu.csv"'
    response.write(u'\ufeff'.encode('utf8'))
    writer = csv.writer(response)
    writer.writerow(['stt_name', 'doidung_name', 'thuchien_name', 'ketthuc_name', 'Ghichu_name'])
    danhmuc_congtacchuyenmon = themmoi_m.objects.all().order_by('-stt_name')
    Myfilter = tongsofilter(request.GET, queryset=danhmuc_congtacchuyenmon)
    danhmuc_congtacchuyenmon = Myfilter.qs
    danhmuc_congtacchuyenmon = danhmuc_congtacchuyenmon.values_list('stt_name', 'doidung_name', 'thuchien_name', 'ketthuc_name', 'Ghichu_name')
    for doidung_name in danhmuc_congtacchuyenmon:
      writer.writerow(doidung_name)
    return response

# Bằng cấp chứng chỉ
def bangcap(request):
    bangcap_data = bangcap_m.objects.order_by('stt_bc')
    form = forms.bangcap_f()

    if request.method == 'POST':
        form = forms.bangcap_f(request.POST)
        if form.is_valid():
            form.save(commit=True)
    # view pages
    page = request.GET.get('page', 1)
    paginator = Paginator(bangcap_data, 9)
    try:
        page_hienthi = paginator.page(page)
    except PageNotAnInteger:
        page_hienthi =  paginator.page(1)
    except EmptyPage:
        page_hienthi = paginator.page(paginator.num_pages)

    return render(request,'QLVB2_APP/bangcap.html',{'form':form,'bangcap_data':bangcap_data, 'page_hienthi':page_hienthi})

def taisan(request):
#     taisan_data = taisan_m.objects.order_by('-stt_ts')
#     form = forms.taisan_f()

#     if request.method == 'POST':
#         form = forms.taisan_f(request.POST)
#         if form.is_valid():
#             form.save(commit=True)

# # pages
#     page = request.GET.get('page', 1)
#     paginator = Paginator(taisan_data,5)
#     try:
#         page_hienthi = paginator.page(page)
#     except PageNotAnInteger:
#         page_hienthi =  paginator.page(1)
#     except EmptyPage:
#         page_hienthi = paginator.page(paginator.num_pages)
#     return render(request,'QLVB2_APP/taisan.html',
#                  {'form':form,'taisan_data':taisan_data, 'page_hienthi':page_hienthi})
    return render(request,'QLVB2_APP/taisan.html')


@login_required(login_url='QLVB2_APP:login')
def congtacchuyenmon(request):
    danhmuc_congtacchuyenmon = themmoi_m.objects.order_by('-stt_name')[:10]
    return render(request,'QLVB2_APP/congtacchuyenmon.html', context={'congtacchuyenmon_record':danhmuc_congtacchuyenmon})


# @login_required(login_url='QLVB2_APP:login')
def tongsocongviec(request):
    danhmuc_congtacchuyenmon = themmoi_m.objects.order_by('-stt_name').order_by('-stt_name')
    Myfilter = tongsofilter(request.GET, queryset=danhmuc_congtacchuyenmon)
    danhmuc_congtacchuyenmon = Myfilter.qs
    return render(request, 'QLVB2_APP/tongsocongviec.html', context={'congtacchuyenmon_record':danhmuc_congtacchuyenmon,
                                                                    'Myfilter':Myfilter})

# @login_required(login_url='QLVB2_APP:login')
def hoanthanh(request):
    danhmuc_congtacchuyenmon = themmoi_m.objects.filter(tiendo_name='2').order_by('-stt_name')
    Myfilter = tongsofilter(request.GET, queryset=danhmuc_congtacchuyenmon)
    danhmuc_congtacchuyenmon = Myfilter.qs
    return render(request, 'QLVB2_APP/hoanthanh.html',context={'congtacchuyenmon_record':danhmuc_congtacchuyenmon,
                                                               'Myfilter':Myfilter})

# @login_required(login_url='QLVB2_APP:login')
def dangthuchien(request):
    danhmuc_congtacchuyenmon = dangthuchien = themmoi_m.objects.filter(tiendo_name='1').order_by('-stt_name')
    Myfilter = tongsofilter(request.GET, queryset=danhmuc_congtacchuyenmon)
    danhmuc_congtacchuyenmon = Myfilter.qs
    page = request.GET.get('page', 1)
    paginator = Paginator(danhmuc_congtacchuyenmon, 5)
    try:
        page_hienthi = paginator.page(page)
    except PageNotAnInteger:
        page_hienthi =  paginator.page(1)
    except EmptyPage:
        page_hienthi = paginator.page(paginator.num_pages)


    return render(request, 'QLVB2_APP/dangthuchien.html',context={'congtacchuyenmon_record':danhmuc_congtacchuyenmon,
                                                                  'Myfilter':Myfilter, 'page_hienthi':page_hienthi})

# @login_required(login_url='QLVB2_APP:login')
def chamtiendo(request):
    danhmuc_congtacchuyenmon = themmoi_m.objects.filter(tiendo_name='3').order_by('-stt_name')
    Myfilter = tongsofilter(request.GET, queryset=danhmuc_congtacchuyenmon)
    danhmuc_congtacchuyenmon = Myfilter.qs
    return render(request, 'QLVB2_APP/chamtiendo.html',context={'congtacchuyenmon_record':danhmuc_congtacchuyenmon,
                                                                'Myfilter':Myfilter})

def giahan(request):
    danhmuc_congtacchuyenmon = themmoi_m.objects.filter(tiendo_name='4').order_by('-stt_name')
    Myfilter = tongsofilter(request.GET, queryset=danhmuc_congtacchuyenmon)
    danhmuc_congtacchuyenmon = Myfilter.qs
    return render(request, 'QLVB2_APP/chamtiendo.html',context={'congtacchuyenmon_record':danhmuc_congtacchuyenmon,
                                                                'Myfilter':Myfilter})


# @login_required(login_url='QLVB2_APP:login')
def lienhe(request):
    return render(request, 'QLVB2_APP/lienhe.html')


@login_required(login_url='QLVB2_APP:login')
def nhapdulieu_chuyenmon(request):
    danhmuc_congtacchuyenmon = themmoi_m.objects.filter(tiendo_name='3').order_by('-stt_name')[:7]
    tiendo_data = tiendo.objects.all()
    thuchien_data = thuchien_m.objects.all()
    form = forms.themmoi_f()

    if request.method == 'POST':
        form = forms.themmoi_f(request.POST)
        if form.is_valid():
            form.save(commit=True)
    return render(request,'QLVB2_APP/nhapdulieuchuyenmon.html',
                 {'form':form,'congtacchuyenmon_record':danhmuc_congtacchuyenmon,
                 'tiendo_data': tiendo_data,'thuchien_data':thuchien_data})

QLVB-V1/templates/QLVB2_APP/2_navbar.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-secondary">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'index' %}" class="nav-link">Trang chủ</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'QLVB2_APP:upload' %}" class="nav-link">Chia sẻ tài nguyên</a>
      </li>
    </ul>
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3" method="get">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" id = "doidung_name" name = "doidung_name" placeholder="Tìm kiếm" values="{{Myfilter.doidung_name}}">
          <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->

  </nav>

QLVB-V1/templates/QLVB2_APP/5_footer.html
<footer class="main-footer">
    <strong>Bản quyền &copy; 2020 <a href="http://google.com">Phòng Giám sát an ninh mạng</a>.</strong>
    <!-- All rights reserved. -->
    <div class="float-right d-none d-sm-inline-block">
      <b>Phiên bản
      </b> 2.5.2020
    </div>
</footer>

QLVB-V1/templates/QLVB2_APP/dangthuchien.html
<!DOCTYPE html>
{% extends "QLVB2_APP/base.html" %}
  {% block body_block %}
    {% load static %}
</br>
  <div class="content">

    <!-- <div class="container-fluid"> -->
      <div class="row">
        <!-- thay đổi chiều rộng ở đây (giá trị 12 full, 6 là 2 ô) -->
        <div class="col-12">

                    <div class="card">
                      <div class="card-body">
                        {% if page_hienthi %}
                        <table  class="table table-bordered table-hover">
                          <thead>
                          <tr>
                            <th class = "align-middle text-center" >STT</th>
                            <th class = "align-middle text-center" style="width: 30%">Nội dung thực hiện</th>
                            <th class = "align-middle text-center" style="width: 10%">Thực hiện</th>
                            <th class = "align-middle text-center" style="width: 10%">Thời gian Kết thúc</th>
                            <th class = "align-middle text-center" style="width: 10%">Kết quả</th>
                            <th class = "align-middle text-center" style="width: 30%">Ghi chú (Căn cứ triển khai)</th>
                            <th class = "align-middle text-center" style="width: 20%">Chỉnh sửa</th>
                          </tr>
                        </thead>
                        {% for x in page_hienthi %}
                        <tbody>
                            <tr>
                              <td class = "align-middle text-center" >{{ x.stt_name }}</td>
                              <td class = "align-middle" style="text-align: justify;width: 30%">{{ x.doidung_name}}</td>
                              <td class = " align-middle text-center" style="width: 10%">{{ x.thuchien_name }}</td>
                              <td class = " align-middle text-center" style="width: 10%">{{ x.ketthuc_name|date:"d/n/Y" }}</td>
                              <td class = " align-middle text-center" style="width: 10%">{{ x.tiendo_name}}</td>
                              <td class = " align-middle " style="text-align: justify;width: 30%">{{ x.Ghichu_name}}</td>
                              <td class = " align-middle text-center" style="width: 20%" >
                                <a href="{% url 'QLVB2_APP:edit_congviec' x.stt_name %}" class="btn btn-warning btn-sm"> Sửa</a>
                                <a href="{% url 'QLVB2_APP:delete_congviec' x.stt_name %}" class="btn btn-sm btn-danger"> Xóa</a>
                              </td>
                            </tr>
                          </tbody>
                      {% endfor %}
                          {% if page_hienthi.has_other_pages %}

                          <ul class="pagination col-1">
                            {% if page_hienthi.has_previous %}
                              <li><a class="form-control" href="?page={{ page_hienthi.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                              <li class="disabled form-control"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in page_hienthi.paginator.page_range %}
                              {% if page_hienthi.number == i %}
                                <li class="active text-red form-control"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                              {% else %}
                                <li><a class="form-control" href="?page={{ i }}">{{ i }}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if page_hienthi.has_next %}
                              <li><a class="form-control" href="?page={{ page_hienthi.next_page_number }}">&raquo;</a></li>
                              {% else %}
                              <li class="disabled form-control"><span>&raquo;</span></li>

                            {% endif %}
                            <!-- <span ><a class="form-control text-blue" href="#">Export</a></span> -->
                          </ul>
                      {% endif %}
                    </table>
                      {% else %}
                      <p>Không tìm thấy dữ liệu nào.</p>
                      {% endif %}
                      </div>
                    </div>
                    <!-- /.card -->
                  </div>
        <!-- /.col-md-6 -->
        <!-- thay đổi chiều rộng ở đây giá trị 12 là full, 6 là 2 ô -->
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    <!-- </div> -->
    <!-- /.container-fluid -->
  </div>
  {% endblock %}

QLVB-V1/templates/QLVB2_APP/delete_BC.html
<!DOCTYPE html>
{% extends "QLVB2_APP/base.html" %}
  {% block body_block %}
    {% load static %}
    <div class="row">
      <!-- thay đổi chiều rộng ở đây (giá trị 12 full, 6 là 2 ô) -->
      <div class="col-lg-12">
        <div class="card">
         <div class="card-body">
			<p>Cán bộ đã chắc chắn muốn xóa "{{delete_bangcap}}" chưa?</p>
			<form action="{% url 'QLVB2_APP:delete_bangcap' delete_bangcap.stt_bc  %}" method="POST">
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'QLVB2_APP:bangcap' %}">Trở về</a>
				<input class="btn btn-danger" type="submit" name="Confirm"></iput>

			</form>
    </div>
    </div>
    </div>
  </div>
{% endblock %}

QLVB-V1/templates/QLVB2_APP/giahan.html
<!DOCTYPE html>
{% extends "QLVB2_APP/base.html" %}
  {% block body_block %}
    {% load static %}
</br>
  <div class="content">

    <div class="container-fluid">
      <div class="row">
        <!-- thay đổi chiều rộng ở đây (giá trị 12 full, 6 là 2 ô) -->
        <div class="col-lg-12">

                    <div class="card">
                      <div class="card-body">
                        {% if congtacchuyenmon_record %}
                        <table  class="table table-bordered table-hover">
                          <thead>
                          <tr>
                            <th class = "align-middle text-center" >STT</th>
                            <th class = "align-middle text-center" style="width: 30%">Nội dung thực hiện</th>
                            <th class = "align-middle text-center" style="width: 10%">Thực hiện</th>
                            <th class = "align-middle text-center" style="width: 10%">Thời gian Kết thúc</th>
                            <th class = "align-middle text-center" style="width: 10%">Kết quả</th>
                            <th class = "align-middle text-center" style="width: 30%">Ghi chú (Căn cứ triển khai)</th>
                            <th class = "align-middle text-center" style="width: 20%">Chỉnh sửa</th>
                          </tr>
                        </thead>
                        {% for x in congtacchuyenmon_record %}
                        <tbody>
                            <tr>
                              <td class = "align-middle text-center" >{{ x.stt_name }}</td>
                              <td class = "align-middle" style="text-align: justify;width: 30%">{{ x.doidung_name}}</td>
                              <td class = " align-middle text-center" style="width: 10%">{{ x.thuchien_name }}</td>
                              <td class = " align-middle text-center" style="width: 10%">{{ x.ketthuc_name|date:"d/n/Y" }}</td>
                              <td class = " align-middle text-center" style="width: 10%">{{ x.tiendo_name}}</td>
                              <td class = " align-middle " style="text-align: justify;width: 30%">{{ x.Ghichu_name}}</td>
                              <td class = " align-middle text-center" style="width: 20%" >
                                <a href="{% url 'QLVB2_APP:edit_congviec' x.stt_name %}" class="btn btn-warning btn-sm"> Sửa</a>
                                <a href="{% url 'QLVB2_APP:delete_congviec' x.stt_name %}" class="btn btn-sm btn-danger"> Xóa</a>
                              </td>
                            </tr>
                          </tbody>
                      {% endfor %}
                    </table>
                      {% else %}
                      <p>Không tìm thấy dữ liệu nào.</p>
                      {% endif %}
                      </div>
                    </div>
                    <!-- /.card -->
              <!-- /.card -->

        </div>
        <!-- /.col-md-6 -->
        <!-- thay đổi chiều rộng ở đây giá trị 12 là full, 6 là 2 ô -->
        <div class="col-lg-12">
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </div>
  {% endblock %}