QLVB-V1/QLVB2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from QLVB2_APP import views
from offenses import views 
# import QLVB2_APP , offenses

urlpatterns = [
    url('admin/', admin.site.urls),
    # url('^$',ql.views.index, name='index'),
    url('',include('QLVB2_APP.urls')),
    # url('',include('offenses.urls')),
]

QLVB-V1/QLVB2_APP/urls.py
from django.conf.urls import url
from django.urls import path
from QLVB2_APP import views
from .views import *
from offenses.views import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'QLVB2_APP'

urlpatterns = [
    url('register/', views.register, name='register'),
    url('login/', views.login, name='login'),
    url('logoutUser/', views.logoutUser, name='logout'),

    url(r'^$',views.index, name='index'),
    url(r'^congtacchuyenmon/$', views.congtacchuyenmon, name='congtacchuyenmon'),
    url(r'^tongsocongviec/$',views.tongsocongviec, name='tongsocongviec'),
    url(r'^hoanthanh/$', views.hoanthanh, name='hoanthanh'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^dangthuchien/$', views.dangthuchien, name='dangthuchien'),
    url(r'^chamtiendo/$', views.chamtiendo, name='chamtiendo'),
    url(r'^giahan/$', views.giahan, name='giahan'),
    url(r'^nhapdulieuchuyenmon/$', views.nhapdulieu_chuyenmon, name='nhapdulieu_chuyenmon'),
    url(r'^bangcap/$', views.bangcap, name='bangcap'),
    url(r'^taisan/$', views.taisan, name='taisan'),
    url(r'^dulieubaocaotuan/$', views.dulieubaocaotuan, name='dulieubaocaotuan'),


    path('edit_congviec/<str:pk>/', views.edit_congviec, name="edit_congviec"),
    path('delete_congviec/<str:pk>/', views.delete_congviec, name="delete_congviec"),

    path('edit_taisan/<str:pk>/', views.edit_taisan, name="edit_taisan"),
    path('delete_taisan/<str:pk>/', views.delete_taisan, name="delete_taisan"),

    path('edit_bangcap/<str:pk>/', views.edit_bangcap, name="edit_bangcap"),
    path('delete_bangcap/<str:pk>/', views.delete_bangcap, name="delete_bangcap"),

    path('edit_bctuan/<str:pk>/', views.edit_bctuan, name="edit_bctuan"),


    url(r'^csv/$', views.export_csv, name='export_csv'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

QLVB-V1/offenses/urls.py
from . import views
from django.conf.urls import url
from django.urls import path

app_name = 'offenses'
urlpatterns = [
    # path('', views.index, name='offenses'),
    url(r'^$',views.index, name='offenses'),
    ]

QLVB-V1/offenses/models.py
from django.db import models

# Create your models here.

QLVB-V1/offenses/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'QLVB2_APP/taisan.html')

QLVB-V1/templates/offenses/1_base.html
{% load static %}
<!DOCTYPE html>
<html>
{% comment %} block css {% endcomment %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link type="text/css" rel="stylesheet" href="#" media="all">
  <title> Phòng Giám sát an ninh mạng </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/fontawesome-free/css/all.min.css" %} "/>
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" %}"/>
  <link rel="stylesheet" href="{% static "admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" %}"/>
  <!-- Theme style -->
  <!-- daterange picker -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/daterangepicker/daterangepicker.css" %}"/>
  <!-- Ionicons -->
  <!-- <link rel="stylesheet" href="{% static "admin-lte/dist/css/ionicons.min.css" %}"/> -->
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}"/>
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %} "/>
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/jqvmap/jqvmap.min.css" %}"/>
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "admin-lte/dist/css/adminlte.min.css" %}"/>

  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}"/>
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/daterangepicker/daterangepicker.css" %}"/>
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "admin-lte/plugins/summernote/summernote-bs4.css" %}"/>
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet" />
  <!-- <link rel="stylesheet" href="{% static "admin-lte/dist/css/google.css" %}"/> -->
  {% block css_block %}

  {% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        {% include 'QLVB2_APP/3_slidebar.html' %}
        {% include 'QLVB2_APP/2_navbar.html' %}
      <div class="content-wrapper ">
        {% block body_block %}
        {% endblock %}
      </div>
      {% include 'QLVB2_APP/5_footer.html' %}
      <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
      </aside>
    </div>
<!-- jQuery -->
<script src="{% static "admin-lte/plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "admin-lte/plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "admin-lte/plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "admin-lte/plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "admin-lte/plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "admin-lte/plugins/jqvmap/maps/jquery.vmap.usa.js"%}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "admin-lte/plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "admin-lte/plugins/moment/moment.min.js" %}"></script>
<!-- <script src="{% static "admin-lte/plugins/daterangepicker/daterangepicker.js" %}"></script> -->
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "admin-lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "admin-lte/plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "admin-lte/dist/js/adminlte.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "admin-lte/dist/js/pages/dashboard.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "admin-lte/dist/js/demo.js" %}"></script>
{% block js_block %}

{% endblock %}  
</body>
</html>

QLVB-V1/templates/offenses/2_navbar.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-secondary">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'index' %}" class="nav-link">Trang chủ</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'QLVB2_APP:upload' %}" class="nav-link">Chia sẻ tài nguyên</a>
      </li>
    </ul>
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3" method="get">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" id = "doidung_name" name = "doidung_name" placeholder="Tìm kiếm" values="{{Myfilter.doidung_name}}">
          <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->

  </nav>

QLVB-V1/templates/offenses/3_slidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <div class="brand-link">
      <img src="{% static "admin-lte/dist/img/BCY93x100.png" %} " alt="BCYE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
           <!-- thay đổi giá trị để vừa với menu search:    .text-sm{font-size -->
           {% if user.is_authenticated %}
           <span class="brand-text font-weight-dark text-warning"> {{request.user.last_name}} {{request.user.first_name}} </span></br>
           <a class="brand-text font-weight-dark text-danger" href="{% url 'QLVB2_APP:logout' %}" >Đăng xuất</a>
         {% else %}
         <a href="{% url 'QLVB2_APP:login' %}" class="brand-text font-weight-dark text-blue">Đăng nhập</a>
       {% endif %}
        <!-- <span class="brand-text font-weight-dark"> TRUNG TÂM CNTT&GSANM </span></br>
        <span class="brand-text font-weight-dark"><strong> PHÒNG GIÁM SÁT AN NINH MẠNG </strong></span></br> -->
    </div>
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <!-- <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/static/admin-lte/dist/img/user3-128x128.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          {% if user.is_authenticated %}
          <li> <span class="text-primary"> Xin chào {{request.user}} </span>|
          <a href="{% url 'QLVB2_APP:logout' %} class="class="text-danger">Đăng xuất
          </a>
        </li>
        {% else %}
        <li >
        <a href="{% url 'QLVB2_APP:login' %}" class="text-primary">Đăng nhập
        </a>
      </li>
      {% endif %}
        </div>
      </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-legacy" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item has-treeview">
            <a href="{% url 'QLVB2_APP:index' %}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Thống kê nhiệm vụ
                <!-- <i class="right fas fa-angle-left"></i> -->
              </p>
            </a>
            <li class="nav-item has-treeview">
            <a href="{% url 'QLVB2_APP:dulieubaocaotuan' %}" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Công việc theo tuần
              </p>
            </a>
          </li>
          <!-- <li class="nav-item has-treeview">
          <a href="{% url 'QLVB2_APP:nhapdulieu_chuyenmon' %}" class="nav-link">
            <i class="nav-icon fas fa-chart-pie"></i>
            <p>
              Số liệu giám sát
            </p>
          </a>
        </li> -->
        <li class="nav-item has-treeview">
        <a href="#" class="nav-link">
          <i class="nav-icon fas fa-chart-pie"></i>
          <p>
            Quản lý tài sản
          </p>
        </a>
      </li>
        <li class="nav-item has-treeview">
        <a href="{% url 'QLVB2_APP:bangcap' %}" class="nav-link">
          <i class="nav-icon fas fa-table"></i>
          <p>
            Bằng cấp chứng chỉ
          </p>
        </a>
      </li>
      <li class="nav-item has-treeview">
        {% comment %} <a href="{% url 'QLVB2_APP:taisan' %}" class="nav-link"> {% endcomment %}
        <a href="{% url 'offenses:offenses' %}" class="nav-link">
          <i class="nav-icon fas fa-table"></i>
          <p>
            Offenses
          </p>
        </a>
      </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

QLVB-V1/templates/offenses/5_footer.html
<footer class="main-footer">
    <strong>Bản quyền &copy; 2020 <a href="http://google.com">Phòng Giám sát an ninh mạng</a>.</strong>
    <!-- All rights reserved. -->
    <div class="float-right d-none d-sm-inline-block">
      <b>Phiên bản
      </b> 2.5.2020
    </div>
</footer>